apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: transactions
  name: transactions
spec:
  ports:
    - name: "2115"
      port: 2115
      targetPort: 2115
  selector:
    io.kompose.service: transactions
status:
  loadBalancer: {}
