version: '3.8'

services:
  users:
    image: xvisox/brokerapp-users:latest
    ports:
      - "2116:2116"
    environment:
      - SERVER_PORT=2116
      - POSTGRES_HOST=psql-server
      - POSTGRES_USER=brokerapp
      - POSTGRES_PASSWORD=brokerapp
      - POSTGRES_DB=brokerapp
    depends_on:
      - psql-server

  transactions:
    image: xvisox/brokerapp-transactions:latest
    ports:
      - "2115:2115"
    environment:
      - SERVER_PORT=2115
      - POSTGRES_HOST=psql-server
      - POSTGRES_USER=brokerapp
      - POSTGRES_PASSWORD=brokerapp
      - POSTGRES_DB=brokerapp
      - KAFKA_HOST=kafka-cluster
      - KAFKA_PORT=9092
      - USERS_HOST=users
      - USERS_PORT=2116
    depends_on:
      - psql-server
      - kafka-cluster
      - users

  history:
    image: xvisox/brokerapp-history:latest
    ports:
      - "2117:2117"
    environment:
      - SERVER_PORT=2117
      - POSTGRES_HOST=psql-server
      - POSTGRES_USER=brokerapp
      - POSTGRES_PASSWORD=brokerapp
      - POSTGRES_DB=brokerapp
      - KAFKA_HOST=kafka-cluster
      - KAFKA_PORT=9092
      - USERS_HOST=users
      - USERS_PORT=2116
    depends_on:
      - psql-server
      - kafka-cluster
      - users

  gateway:
    image: xvisox/brokerapp-gateway:latest
    ports:
      - "8080:8080" # FIXME: might need to change this port to $PORT from GCP

  psql-server:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=brokerapp
      - POSTGRES_USER=brokerapp
      - POSTGRES_DB=brokerapp

  kafka-cluster:
    image: moeenz/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=kafka-cluster
