eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - Authorization
              - Content-Type
              - Cache-Control
              - X-Requested-With
              - accept
              - Origin
              - Access-Control-Request-Method
              - Access-Control-Request-Headers
            maxAge: 3600
      discovery:
        locator:
          enabled: true
      routes: # FIXME: this code only works for docker-compose and k8s, not for local development
        - id: transactions
          uri: http://transactions:2115
          predicates:
            - Path=/api/v1/transactions/**
        - id: users
          uri: http://users:2116
          predicates:
            - Path=/api/v1/users/**
        - id: history
          uri: http://history:2117
          predicates:
            - Path=/api/v1/history/**
  config:
    import: optional:configserver:http://localhost:8888
