eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: transactions
          uri: http://localhost:2115
          predicates:
            - Path=/api/v1/transactions/**
        - id: users
          uri: http://localhost:2116
          predicates:
            - Path=/api/v1/users/**
  config:
    import: optional:configserver:http://localhost:8888

